### ISSUE TITLE
does this work with 1.9.2

### ISSUE THREAD

**Issue by rkumar** [nu7hatch/gmail#1]
ruby-1.9.2-head > Gmail.connect("rahulxxx@gmail.com","xxx") do |gmail|
ruby-1.9.2-head >     gmail.inbox.count
ruby-1.9.2-head ?>  end
Net::IMAP::BadResponseError: Unknown command z5if11396491vco.62

and

ruby-1.9.2-head > gmail = Gmail.connect!("rahulxxxx@gmail.com","xxxxx")
NoMethodError: undefined method `data' for "Couldn't login to given GMail account: rahulxxxx@gmail.com

(I am on a macosx snow leopard, using rvm 1.9.2)

**Comment by bootstraponline** [comment]
This issue was moved to gmailgem/gmail#1
